adding better error handling to CI config

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -10,10 +10,17 @@ workflows:
             - run:
                 name: set image tag 
                 command: |
-                  if [ $CIRCLE_BRANCH == "master" ]; then
+                  if [[ -v $CIRCLE_TAG]] && [[ -v $CIRCLE_BRANCH ]]; then
+                    echo "tagging a feature branch is not permitted"
+                    exit 1
+                  fi
+                  if [[ -v $CIRCLE_TAG ]]; then
                     echo 'export IMAGE_TAG=$(echo $CIRCLE_TAG | tr -d v)' >> $BASH_ENV
-                  else
+                  elif [[ -v $CIRCLE_BRANCH ]]; then 
                     echo 'export IMAGE_TAG=$CIRCLE_BRANCH' >> $BASH_ENV
+                  else
+                    echo "ABORTING. Neither git tag nor feature branch found"
+                    exit 1
                   fi
           lint-dockerfile: true
           image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
